version: '3.8'

services:
  
  # nginx
  nginx:
    build:
      context: ./nginx/
      args: 
        CONFIG_FILE: nginx.conf
    hostname: nginx
    container_name: nginx
    ports:
      - '60080:80'

  # internal
  internal:
    build:
      context: ./nginx/
      args: 
        CONFIG_FILE: internal.conf
    hostname: internal
    container_name: internal

  netdata:
    build: ./netdata/
    ports:
      - 19999:19999
    hostname: netdata
    container_name: netdata