version: '3.8'

services:
  
  # nginx with upstream 1.0
  nginx10:
    build:
      context: ./nginx/
      args: 
        CONFIG_FILE: 1.0.conf
    hostname: nginx10
    container_name: nginx10
    ports:
      - '60010:80'

  # nginx with upstream 1.1
  nginx11:
    build:
      context: ./nginx/
      args: 
        CONFIG_FILE: 1.1.conf
    hostname: nginx11
    container_name: nginx11
    ports:
      - '60011:80'

  # internal http server
  internal-http-server:
    build:
      context: ./nginx/
      args: 
        CONFIG_FILE: internal-http-server.conf
    hostname: internal-http-server
    container_name: internal-http-server

  netdata:
    build: ./netdata/
    ports:
      - 19999:19999